modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Evoslab/Cookielicious/issues"

[[mods]]
modId="cookielicious"
version="${file.jarVersion}"
displayName="Cookielicious"
logoFile="cookielicious.png"
credits="Evo, Stardust, AvocadoSpud, Nary, EltrutLikes, JustinPlayzz, Uraneptus"
authors="Evo's Lab"
description='''
Cookielicious is an addon for Neapolitan that adds more cookie themed items.
'''
itemIcon="cookielicious:cookie_tiles" #catalouge

[modproperties.cookielicious]
configuredBackground= "cookielicious:textures/blocks/cookie_tiles.png" #configured

[[dependencies.cookielicious]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="neapolitan" 
    mandatory=true 
    versionRange="[4.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="blueprint"
    mandatory=true
    versionRange="[6.1.2,)"
    ordering="AFTER"
    side="BOTH"