modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Evoslab/Cookielicious/issues"

[[mods]]
modId="cookielicious"
version="${file.jarVersion}"
displayName="Cookielicious"
logoFile="cookielicious.png"
credits="Evo, Stardust, AvocadoSpud, Nary, EltrutLikes, JustinPlayzz"
authors="Evo's Lab"
description='''
Cookielicious is an addon for Neapolitan that adds more cookie themed items.
'''
itemIcon="cookielicious:cookie_tiles" #catalouge

[modproperties.cookielicious]
configuredBackground= "cookielicious:textures/blocks/cookie_tiles.png" #configured

[[dependencies.cookielicious]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="neapolitan" 
    mandatory=true 
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="blueprint"
    mandatory=true
    versionRange="[5.4.0,)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.cookielicious]]
    modId="differentiate"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="AFTER"
    side="BOTH"